sudo: false

cache:
    directories:
        - $HOME/doxygen

before_script:
    # download doxygen 1.8.12
    - mkdir -p $HOME/doxygen
    - cd $HOME/doxygen
    - ls doxygen* >/dev/null 2>&1 || curl -L ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.linux.bin.tar.gz | tar xz

script:
    - cd $TRAVIS_BUILD_DIR
    - echo "TODO need to build testing with samples"

before_deploy:
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"

deploy:
    provider: script
    overwrite: true
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.travis.d/deploy_docs.sh
    on:
        tags: false
        branch:
            - master
